### ISSUE TITLE
Fixed some memory leaks

### ISSUE THREAD

**Issue by Nuzhny007** [yu-lab-vt/muSSP#1]
Hi!
Thank you for this awesome work!
I'm a contributor to the open source project for multi-object tracking: https://github.com/Smorodov/Multitarget-tracker
And I want to integrate your awesome algorithm to this project. But in your code are some memory leaks (new without delete etc). I made some fixes in my fork: https://github.com/Nuzhny007/muSSP
Also was removed unused functions, fixed code style... And I can crate pull request with all fixes - what do you think about it?

**Comment by yu-lab-vt** [comment]
Hi,
We are happy to know that our work can contribute to the Multitarget-tracker project. Thanks for your work, and we really appreciate it!

We are open to and appreciate everyone's contribution to muSSP. You can just create the pull requests to the "dev" branch. We will merge the fixes to the "master" branch after testing some samples.

Thanks!

**Comment by Nuzhny007** [comment]
https://github.com/yu-lab-vt/muSSP/pull/2

**Comment by yu-lab-vt** [comment]
Hi, Nuzhny007,

There is an error caused by the 'abs' function in Graph.cpp in your code. It will wrongly round the input float number to integers and thus results in a non-optimal solution. I have fixed it and now it should be good. I have merged your changes to the master branch. 

Thank you again!
