### ISSUE TITLE
Writing program output to file

### ISSUE THREAD

**Issue by alexisrozhkov** [yu-lab-vt/muSSP#10]
Can you please give an example of how to write resulting trajectories to file? 

According to the `main.cpp`, it seems that providing more than 2 command-line arguments should cause the call to `print_solution()`, and it indeed happens, but it doesn't write anything to file and the program terminates with a segmentation fault.

I've used provided file `input_MOT_seq07_followme.txt` as input, in case it helps.

**Comment by yu-lab-vt** [comment]
The issue is noted. We will come back to you soon.

**Comment by ccwang92** [comment]
Hi Alexey, you can change the line 61 of Graph.cpp from "if (**false**) {" to "if (**true**) {". Then print function should work correctly.

This is because if we want to evaluate or output the flow results, we will need several variables for "org_graph". For finding the min-cost, they are not needed.

Best,

**Comment by alexisrozhkov** [comment]
Thank you for a prompt feedback, it resolves the issue!
